package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingGoods;
import com.walrus.manufacturing.db.domain.ManufacturingGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    int insert(ManufacturingGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    ManufacturingGoods selectOneByExample(ManufacturingGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    ManufacturingGoods selectOneByExampleSelective(@Param("example") ManufacturingGoodsExample example, @Param("selective") ManufacturingGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    ManufacturingGoods selectOneByExampleWithBLOBs(ManufacturingGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    List<ManufacturingGoods> selectByExampleSelective(@Param("example") ManufacturingGoodsExample example, @Param("selective") ManufacturingGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    List<ManufacturingGoods> selectByExampleWithBLOBs(ManufacturingGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    List<ManufacturingGoods> selectByExample(ManufacturingGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    ManufacturingGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    ManufacturingGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    ManufacturingGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingGoods record, @Param("example") ManufacturingGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ManufacturingGoods record, @Param("example") ManufacturingGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingGoods record, @Param("example") ManufacturingGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ManufacturingGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}