package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingCouponUser;
import com.walrus.manufacturing.db.domain.ManufacturingCouponUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    int insert(ManufacturingCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    ManufacturingCouponUser selectOneByExample(ManufacturingCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    ManufacturingCouponUser selectOneByExampleSelective(@Param("example") ManufacturingCouponUserExample example, @Param("selective") ManufacturingCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    List<ManufacturingCouponUser> selectByExampleSelective(@Param("example") ManufacturingCouponUserExample example, @Param("selective") ManufacturingCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    List<ManufacturingCouponUser> selectByExample(ManufacturingCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    ManufacturingCouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    ManufacturingCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    ManufacturingCouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingCouponUser record, @Param("example") ManufacturingCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingCouponUser record, @Param("example") ManufacturingCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}