package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingKeyword;
import com.walrus.manufacturing.db.domain.ManufacturingKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    int insert(ManufacturingKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    ManufacturingKeyword selectOneByExample(ManufacturingKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    ManufacturingKeyword selectOneByExampleSelective(@Param("example") ManufacturingKeywordExample example, @Param("selective") ManufacturingKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    List<ManufacturingKeyword> selectByExampleSelective(@Param("example") ManufacturingKeywordExample example, @Param("selective") ManufacturingKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    List<ManufacturingKeyword> selectByExample(ManufacturingKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    ManufacturingKeyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    ManufacturingKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    ManufacturingKeyword selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingKeyword record, @Param("example") ManufacturingKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingKeyword record, @Param("example") ManufacturingKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}