package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingSystem;
import com.walrus.manufacturing.db.domain.ManufacturingSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    int insert(ManufacturingSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    ManufacturingSystem selectOneByExample(ManufacturingSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    ManufacturingSystem selectOneByExampleSelective(@Param("example") ManufacturingSystemExample example, @Param("selective") ManufacturingSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    List<ManufacturingSystem> selectByExampleSelective(@Param("example") ManufacturingSystemExample example, @Param("selective") ManufacturingSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    List<ManufacturingSystem> selectByExample(ManufacturingSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    ManufacturingSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    ManufacturingSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    ManufacturingSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingSystem record, @Param("example") ManufacturingSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingSystem record, @Param("example") ManufacturingSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}