package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingGrouponRules;
import com.walrus.manufacturing.db.domain.ManufacturingGrouponRulesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingGrouponRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    int insert(ManufacturingGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    ManufacturingGrouponRules selectOneByExample(ManufacturingGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    ManufacturingGrouponRules selectOneByExampleSelective(@Param("example") ManufacturingGrouponRulesExample example, @Param("selective") ManufacturingGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    List<ManufacturingGrouponRules> selectByExampleSelective(@Param("example") ManufacturingGrouponRulesExample example, @Param("selective") ManufacturingGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    List<ManufacturingGrouponRules> selectByExample(ManufacturingGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    ManufacturingGrouponRules selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    ManufacturingGrouponRules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    ManufacturingGrouponRules selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingGrouponRules record, @Param("example") ManufacturingGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingGrouponRules record, @Param("example") ManufacturingGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}