package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingRole;
import com.walrus.manufacturing.db.domain.ManufacturingRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    int insert(ManufacturingRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    ManufacturingRole selectOneByExample(ManufacturingRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    ManufacturingRole selectOneByExampleSelective(@Param("example") ManufacturingRoleExample example, @Param("selective") ManufacturingRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    List<ManufacturingRole> selectByExampleSelective(@Param("example") ManufacturingRoleExample example, @Param("selective") ManufacturingRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    List<ManufacturingRole> selectByExample(ManufacturingRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    ManufacturingRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    ManufacturingRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    ManufacturingRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingRole record, @Param("example") ManufacturingRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingRole record, @Param("example") ManufacturingRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}