package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingGoodsProduct;
import com.walrus.manufacturing.db.domain.ManufacturingGoodsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    int insert(ManufacturingGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    ManufacturingGoodsProduct selectOneByExample(ManufacturingGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    ManufacturingGoodsProduct selectOneByExampleSelective(@Param("example") ManufacturingGoodsProductExample example, @Param("selective") ManufacturingGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    List<ManufacturingGoodsProduct> selectByExampleSelective(@Param("example") ManufacturingGoodsProductExample example, @Param("selective") ManufacturingGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    List<ManufacturingGoodsProduct> selectByExample(ManufacturingGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    ManufacturingGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    ManufacturingGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    ManufacturingGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingGoodsProduct record, @Param("example") ManufacturingGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingGoodsProduct record, @Param("example") ManufacturingGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}