package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingStorage;
import com.walrus.manufacturing.db.domain.ManufacturingStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    int insert(ManufacturingStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    ManufacturingStorage selectOneByExample(ManufacturingStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    ManufacturingStorage selectOneByExampleSelective(@Param("example") ManufacturingStorageExample example, @Param("selective") ManufacturingStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    List<ManufacturingStorage> selectByExampleSelective(@Param("example") ManufacturingStorageExample example, @Param("selective") ManufacturingStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    List<ManufacturingStorage> selectByExample(ManufacturingStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    ManufacturingStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    ManufacturingStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    ManufacturingStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingStorage record, @Param("example") ManufacturingStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingStorage record, @Param("example") ManufacturingStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}