package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingGoodsAttribute;
import com.walrus.manufacturing.db.domain.ManufacturingGoodsAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    int insert(ManufacturingGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    ManufacturingGoodsAttribute selectOneByExample(ManufacturingGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    ManufacturingGoodsAttribute selectOneByExampleSelective(@Param("example") ManufacturingGoodsAttributeExample example, @Param("selective") ManufacturingGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    List<ManufacturingGoodsAttribute> selectByExampleSelective(@Param("example") ManufacturingGoodsAttributeExample example, @Param("selective") ManufacturingGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    List<ManufacturingGoodsAttribute> selectByExample(ManufacturingGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    ManufacturingGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    ManufacturingGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    ManufacturingGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingGoodsAttribute record, @Param("example") ManufacturingGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingGoodsAttribute record, @Param("example") ManufacturingGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}