package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingAddress;
import com.walrus.manufacturing.db.domain.ManufacturingAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    int insert(ManufacturingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    ManufacturingAddress selectOneByExample(ManufacturingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    ManufacturingAddress selectOneByExampleSelective(@Param("example") ManufacturingAddressExample example, @Param("selective") ManufacturingAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    List<ManufacturingAddress> selectByExampleSelective(@Param("example") ManufacturingAddressExample example, @Param("selective") ManufacturingAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    List<ManufacturingAddress> selectByExample(ManufacturingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    ManufacturingAddress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    ManufacturingAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    ManufacturingAddress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingAddress record, @Param("example") ManufacturingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingAddress record, @Param("example") ManufacturingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_address
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}