package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingUser;
import com.walrus.manufacturing.db.domain.ManufacturingUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    int insert(ManufacturingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    ManufacturingUser selectOneByExample(ManufacturingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    ManufacturingUser selectOneByExampleSelective(@Param("example") ManufacturingUserExample example, @Param("selective") ManufacturingUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    List<ManufacturingUser> selectByExampleSelective(@Param("example") ManufacturingUserExample example, @Param("selective") ManufacturingUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    List<ManufacturingUser> selectByExample(ManufacturingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    ManufacturingUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    ManufacturingUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    ManufacturingUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingUser record, @Param("example") ManufacturingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingUser record, @Param("example") ManufacturingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}