package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingAdmin;
import com.walrus.manufacturing.db.domain.ManufacturingAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    int insert(ManufacturingAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    ManufacturingAdmin selectOneByExample(ManufacturingAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    ManufacturingAdmin selectOneByExampleSelective(@Param("example") ManufacturingAdminExample example, @Param("selective") ManufacturingAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    List<ManufacturingAdmin> selectByExampleSelective(@Param("example") ManufacturingAdminExample example, @Param("selective") ManufacturingAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    List<ManufacturingAdmin> selectByExample(ManufacturingAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    ManufacturingAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    ManufacturingAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    ManufacturingAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingAdmin record, @Param("example") ManufacturingAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingAdmin record, @Param("example") ManufacturingAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}