package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingTopic;
import com.walrus.manufacturing.db.domain.ManufacturingTopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    int insert(ManufacturingTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    ManufacturingTopic selectOneByExample(ManufacturingTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    ManufacturingTopic selectOneByExampleSelective(@Param("example") ManufacturingTopicExample example, @Param("selective") ManufacturingTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    ManufacturingTopic selectOneByExampleWithBLOBs(ManufacturingTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    List<ManufacturingTopic> selectByExampleSelective(@Param("example") ManufacturingTopicExample example, @Param("selective") ManufacturingTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    List<ManufacturingTopic> selectByExampleWithBLOBs(ManufacturingTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    List<ManufacturingTopic> selectByExample(ManufacturingTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    ManufacturingTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    ManufacturingTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    ManufacturingTopic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingTopic record, @Param("example") ManufacturingTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ManufacturingTopic record, @Param("example") ManufacturingTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingTopic record, @Param("example") ManufacturingTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ManufacturingTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}