package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingGoodsSpecification;
import com.walrus.manufacturing.db.domain.ManufacturingGoodsSpecificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    int insert(ManufacturingGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    ManufacturingGoodsSpecification selectOneByExample(ManufacturingGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    ManufacturingGoodsSpecification selectOneByExampleSelective(@Param("example") ManufacturingGoodsSpecificationExample example, @Param("selective") ManufacturingGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    List<ManufacturingGoodsSpecification> selectByExampleSelective(@Param("example") ManufacturingGoodsSpecificationExample example, @Param("selective") ManufacturingGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    List<ManufacturingGoodsSpecification> selectByExample(ManufacturingGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    ManufacturingGoodsSpecification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    ManufacturingGoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    ManufacturingGoodsSpecification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingGoodsSpecification record, @Param("example") ManufacturingGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingGoodsSpecification record, @Param("example") ManufacturingGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}