package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingOrderGoods;
import com.walrus.manufacturing.db.domain.ManufacturingOrderGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    int insert(ManufacturingOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    ManufacturingOrderGoods selectOneByExample(ManufacturingOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    ManufacturingOrderGoods selectOneByExampleSelective(@Param("example") ManufacturingOrderGoodsExample example, @Param("selective") ManufacturingOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    List<ManufacturingOrderGoods> selectByExampleSelective(@Param("example") ManufacturingOrderGoodsExample example, @Param("selective") ManufacturingOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    List<ManufacturingOrderGoods> selectByExample(ManufacturingOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    ManufacturingOrderGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    ManufacturingOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    ManufacturingOrderGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingOrderGoods record, @Param("example") ManufacturingOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingOrderGoods record, @Param("example") ManufacturingOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}