package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingCart;
import com.walrus.manufacturing.db.domain.ManufacturingCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    int insert(ManufacturingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    ManufacturingCart selectOneByExample(ManufacturingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    ManufacturingCart selectOneByExampleSelective(@Param("example") ManufacturingCartExample example, @Param("selective") ManufacturingCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    List<ManufacturingCart> selectByExampleSelective(@Param("example") ManufacturingCartExample example, @Param("selective") ManufacturingCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    List<ManufacturingCart> selectByExample(ManufacturingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    ManufacturingCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    ManufacturingCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    ManufacturingCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingCart record, @Param("example") ManufacturingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingCart record, @Param("example") ManufacturingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}