package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingBrand;
import com.walrus.manufacturing.db.domain.ManufacturingBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    int insert(ManufacturingBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    ManufacturingBrand selectOneByExample(ManufacturingBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    ManufacturingBrand selectOneByExampleSelective(@Param("example") ManufacturingBrandExample example, @Param("selective") ManufacturingBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    List<ManufacturingBrand> selectByExampleSelective(@Param("example") ManufacturingBrandExample example, @Param("selective") ManufacturingBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    List<ManufacturingBrand> selectByExample(ManufacturingBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    ManufacturingBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    ManufacturingBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    ManufacturingBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingBrand record, @Param("example") ManufacturingBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingBrand record, @Param("example") ManufacturingBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}