package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingComment;
import com.walrus.manufacturing.db.domain.ManufacturingCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    int insert(ManufacturingComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    ManufacturingComment selectOneByExample(ManufacturingCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    ManufacturingComment selectOneByExampleSelective(@Param("example") ManufacturingCommentExample example, @Param("selective") ManufacturingComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    List<ManufacturingComment> selectByExampleSelective(@Param("example") ManufacturingCommentExample example, @Param("selective") ManufacturingComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    List<ManufacturingComment> selectByExample(ManufacturingCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    ManufacturingComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    ManufacturingComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    ManufacturingComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingComment record, @Param("example") ManufacturingCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingComment record, @Param("example") ManufacturingCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}