package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingAd;
import com.walrus.manufacturing.db.domain.ManufacturingAdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    int insert(ManufacturingAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    ManufacturingAd selectOneByExample(ManufacturingAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    ManufacturingAd selectOneByExampleSelective(@Param("example") ManufacturingAdExample example, @Param("selective") ManufacturingAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    List<ManufacturingAd> selectByExampleSelective(@Param("example") ManufacturingAdExample example, @Param("selective") ManufacturingAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    List<ManufacturingAd> selectByExample(ManufacturingAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    ManufacturingAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    ManufacturingAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    ManufacturingAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingAd record, @Param("example") ManufacturingAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingAd record, @Param("example") ManufacturingAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}