package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingRegion;
import com.walrus.manufacturing.db.domain.ManufacturingRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_region
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_region
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_region
     *
     * @mbg.generated
     */
    int insert(ManufacturingRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_region
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_region
     *
     * @mbg.generated
     */
    ManufacturingRegion selectOneByExample(ManufacturingRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_region
     *
     * @mbg.generated
     */
    ManufacturingRegion selectOneByExampleSelective(@Param("example") ManufacturingRegionExample example, @Param("selective") ManufacturingRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_region
     *
     * @mbg.generated
     */
    List<ManufacturingRegion> selectByExampleSelective(@Param("example") ManufacturingRegionExample example, @Param("selective") ManufacturingRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_region
     *
     * @mbg.generated
     */
    List<ManufacturingRegion> selectByExample(ManufacturingRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_region
     *
     * @mbg.generated
     */
    ManufacturingRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_region
     *
     * @mbg.generated
     */
    ManufacturingRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingRegion record, @Param("example") ManufacturingRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingRegion record, @Param("example") ManufacturingRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingRegion record);
}