package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingCoupon;
import com.walrus.manufacturing.db.domain.ManufacturingCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    int insert(ManufacturingCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    ManufacturingCoupon selectOneByExample(ManufacturingCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    ManufacturingCoupon selectOneByExampleSelective(@Param("example") ManufacturingCouponExample example, @Param("selective") ManufacturingCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    List<ManufacturingCoupon> selectByExampleSelective(@Param("example") ManufacturingCouponExample example, @Param("selective") ManufacturingCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    List<ManufacturingCoupon> selectByExample(ManufacturingCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    ManufacturingCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    ManufacturingCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    ManufacturingCoupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingCoupon record, @Param("example") ManufacturingCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingCoupon record, @Param("example") ManufacturingCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}