package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingPermission;
import com.walrus.manufacturing.db.domain.ManufacturingPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    int insert(ManufacturingPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    ManufacturingPermission selectOneByExample(ManufacturingPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    ManufacturingPermission selectOneByExampleSelective(@Param("example") ManufacturingPermissionExample example, @Param("selective") ManufacturingPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    List<ManufacturingPermission> selectByExampleSelective(@Param("example") ManufacturingPermissionExample example, @Param("selective") ManufacturingPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    List<ManufacturingPermission> selectByExample(ManufacturingPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    ManufacturingPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    ManufacturingPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    ManufacturingPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingPermission record, @Param("example") ManufacturingPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingPermission record, @Param("example") ManufacturingPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}