package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingCollect;
import com.walrus.manufacturing.db.domain.ManufacturingCollectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    int insert(ManufacturingCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    ManufacturingCollect selectOneByExample(ManufacturingCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    ManufacturingCollect selectOneByExampleSelective(@Param("example") ManufacturingCollectExample example, @Param("selective") ManufacturingCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    List<ManufacturingCollect> selectByExampleSelective(@Param("example") ManufacturingCollectExample example, @Param("selective") ManufacturingCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    List<ManufacturingCollect> selectByExample(ManufacturingCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    ManufacturingCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    ManufacturingCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    ManufacturingCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingCollect record, @Param("example") ManufacturingCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingCollect record, @Param("example") ManufacturingCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}