package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingNotice;
import com.walrus.manufacturing.db.domain.ManufacturingNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    int insert(ManufacturingNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    ManufacturingNotice selectOneByExample(ManufacturingNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    ManufacturingNotice selectOneByExampleSelective(@Param("example") ManufacturingNoticeExample example, @Param("selective") ManufacturingNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    List<ManufacturingNotice> selectByExampleSelective(@Param("example") ManufacturingNoticeExample example, @Param("selective") ManufacturingNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    List<ManufacturingNotice> selectByExample(ManufacturingNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    ManufacturingNotice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    ManufacturingNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    ManufacturingNotice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingNotice record, @Param("example") ManufacturingNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingNotice record, @Param("example") ManufacturingNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}