package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingOrder;
import com.walrus.manufacturing.db.domain.ManufacturingOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    int insert(ManufacturingOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    ManufacturingOrder selectOneByExample(ManufacturingOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    ManufacturingOrder selectOneByExampleSelective(@Param("example") ManufacturingOrderExample example, @Param("selective") ManufacturingOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    List<ManufacturingOrder> selectByExampleSelective(@Param("example") ManufacturingOrderExample example, @Param("selective") ManufacturingOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    List<ManufacturingOrder> selectByExample(ManufacturingOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    ManufacturingOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    ManufacturingOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    ManufacturingOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingOrder record, @Param("example") ManufacturingOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingOrder record, @Param("example") ManufacturingOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}