package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingLog;
import com.walrus.manufacturing.db.domain.ManufacturingLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    int insert(ManufacturingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    ManufacturingLog selectOneByExample(ManufacturingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    ManufacturingLog selectOneByExampleSelective(@Param("example") ManufacturingLogExample example, @Param("selective") ManufacturingLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    List<ManufacturingLog> selectByExampleSelective(@Param("example") ManufacturingLogExample example, @Param("selective") ManufacturingLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    List<ManufacturingLog> selectByExample(ManufacturingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    ManufacturingLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    ManufacturingLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    ManufacturingLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingLog record, @Param("example") ManufacturingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingLog record, @Param("example") ManufacturingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}