package com.walrus.manufacturing.db.dao;

import com.walrus.manufacturing.db.domain.ManufacturingFootprint;
import com.walrus.manufacturing.db.domain.ManufacturingFootprintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManufacturingFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    long countByExample(ManufacturingFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    int deleteByExample(ManufacturingFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    int insert(ManufacturingFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    int insertSelective(ManufacturingFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    ManufacturingFootprint selectOneByExample(ManufacturingFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    ManufacturingFootprint selectOneByExampleSelective(@Param("example") ManufacturingFootprintExample example, @Param("selective") ManufacturingFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    List<ManufacturingFootprint> selectByExampleSelective(@Param("example") ManufacturingFootprintExample example, @Param("selective") ManufacturingFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    List<ManufacturingFootprint> selectByExample(ManufacturingFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    ManufacturingFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ManufacturingFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    ManufacturingFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    ManufacturingFootprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManufacturingFootprint record, @Param("example") ManufacturingFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManufacturingFootprint record, @Param("example") ManufacturingFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManufacturingFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManufacturingFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ManufacturingFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturing_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}